### ISSUE TITLE
Anything that uses the official SDK should be clearly flagged as such

### ISSUE THREAD

**Issue by AntonioND** [command-tab/awesome-n64-development#10]
Due to how problematic it is to use the official Nintendo SDK, I wouldn't like to touch it at all if I'm developing something for N64. However, when I look around the list of toolchains and libs, I see a lot of references to it. I think it would be nice to have a clean list of tools that doesn't include that SDK at all. Maybe there could be a checkbox that makes all of the entries disappear?

**Comment by command-tab** [comment]
I think this would be cool, but I can't think of a good way to make this happen with GitHub Pages and Markdown.

**Comment by AntonioND** [comment]
Fair enough. What about some tag like ``[Nintendo SDK]`` so that at least they are easy to spot?
