### ISSUE TITLE
rom64 - command line utility for rom info

### ISSUE THREAD

**Issue by mroach** [command-tab/awesome-n64-development#17]
Hello! Not sure if this can be considered "awesome" but I want to share a utility I've been working on called `rom64`. It's a command-line utility for fetching ROM information in human-readable and machine-readable formats. In addition, it can validate ROMs against a datfile and convert to native (big-endian) format.

I couldn't find a utility that did the things I wanted/needed, so I created one and it's currently in active development.

https://github.com/mroach/rom64

**Comment by command-tab** [comment]
This is great! Excellent work! 👏🏻  I'll add it.

**Comment by command-tab** [comment]
Thank you!

**Comment by mroach** [comment]
Very cool! Thanks! Some of the links on your page were super helpful in working out the details of ROM headers and such.

**Comment by command-tab** [comment]
Now if only I could get GitHub Pages to rebuild for https://n64.dev without error 😩 I haven't changed anything since the previous Markdown file change...

**Comment by command-tab** [comment]
Deployed!
